import { BranchInfo } from "./types";

function daysAgo(days: number): Date {
  const d = new Date();
  d.setDate(d.getDate() - days);
  return d;
}

export const MOCK_PROJECT = {
  id: 42,
  name: "our-platform",
  path_with_namespace: "team/our-platform",
  web_url: "https://gitlab.example.com/team/our-platform",
};

export const MOCK_MR_AUTHORS: Record<string, string> = {
  "feature/user-auth-oauth": "kim.junghyun",
  "bugfix/login-redirect-loop": "park.sooyeon",
  "feature/dashboard-redesign": "lee.minseok",
  "bugfix/api-timeout-handling": "choi.yujin",
  "feature/notifications-v2": "kim.junghyun",
};

export const MOCK_BRANCHES: BranchInfo[] = [
  // Default branch
  {
    name: "main",
    merged: false,
    protected: true,
    isDefault: true,
    lastCommitDate: daysAgo(1),
    lastCommitMessage: "Merge branch 'release/2.4.1'",
    lastCommitAuthor: "ci-bot",
    ageInDays: 1,
    webUrl: "https://gitlab.example.com/team/our-platform/-/tree/main",
  },
  // Protected branches
  {
    name: "develop",
    merged: false,
    protected: true,
    isDefault: false,
    lastCommitDate: daysAgo(2),
    lastCommitMessage: "chore: bump version to 2.4.2-dev",
    lastCommitAuthor: "ci-bot",
    ageInDays: 2,
    webUrl: "https://gitlab.example.com/team/our-platform/-/tree/develop",
  },
  {
    name: "release/2.4.0",
    merged: false,
    protected: true,
    isDefault: false,
    lastCommitDate: daysAgo(15),
    lastCommitMessage: "fix: patch security vulnerability",
    lastCommitAuthor: "lee.minseok",
    ageInDays: 15,
    webUrl: "https://gitlab.example.com/team/our-platform/-/tree/release/2.4.0",
  },
  // Active feature branches (safe)
  {
    name: "feature/user-auth-oauth",
    merged: false,
    protected: false,
    isDefault: false,
    lastCommitDate: daysAgo(3),
    lastCommitMessage: "feat: add Google OAuth provider",
    lastCommitAuthor: "kim.junghyun",
    ageInDays: 3,
    webUrl: "https://gitlab.example.com/team/our-platform/-/tree/feature/user-auth-oauth",
  },
  {
    name: "feature/payment-integration",
    merged: false,
    protected: false,
    isDefault: false,
    lastCommitDate: daysAgo(7),
    lastCommitMessage: "feat: implement Stripe webhook handler",
    lastCommitAuthor: "jung.hyewon",
    ageInDays: 7,
    webUrl: "https://gitlab.example.com/team/our-platform/-/tree/feature/payment-integration",
  },
  {
    name: "feature/mobile-push-notifications",
    merged: false,
    protected: false,
    isDefault: false,
    lastCommitDate: daysAgo(14),
    lastCommitMessage: "feat: add FCM token registration endpoint",
    lastCommitAuthor: "oh.seungmin",
    ageInDays: 14,
    webUrl: "https://gitlab.example.com/team/our-platform/-/tree/feature/mobile-push-notifications",
  },
  // Merged + recent → review
  {
    name: "bugfix/login-redirect-loop",
    merged: true,
    protected: false,
    isDefault: false,
    lastCommitDate: daysAgo(20),
    lastCommitMessage: "fix: resolve redirect loop on expired session",
    lastCommitAuthor: "park.sooyeon",
    ageInDays: 20,
    webUrl: "https://gitlab.example.com/team/our-platform/-/tree/bugfix/login-redirect-loop",
  },
  {
    name: "feature/notifications-v2",
    merged: true,
    protected: false,
    isDefault: false,
    lastCommitDate: daysAgo(25),
    lastCommitMessage: "feat: notification center v2 complete",
    lastCommitAuthor: "kim.junghyun",
    ageInDays: 25,
    webUrl: "https://gitlab.example.com/team/our-platform/-/tree/feature/notifications-v2",
  },
  {
    name: "feature/dashboard-redesign",
    merged: true,
    protected: false,
    isDefault: false,
    lastCommitDate: daysAgo(28),
    lastCommitMessage: "feat: complete dashboard v3 UI",
    lastCommitAuthor: "lee.minseok",
    ageInDays: 28,
    webUrl: "https://gitlab.example.com/team/our-platform/-/tree/feature/dashboard-redesign",
  },
  // Merged + stale → delete-recommended
  {
    name: "bugfix/api-timeout-handling",
    merged: true,
    protected: false,
    isDefault: false,
    lastCommitDate: daysAgo(45),
    lastCommitMessage: "fix: add retry logic for flaky API calls",
    lastCommitAuthor: "choi.yujin",
    ageInDays: 45,
    webUrl: "https://gitlab.example.com/team/our-platform/-/tree/bugfix/api-timeout-handling",
  },
  {
    name: "feature/csv-export",
    merged: true,
    protected: false,
    isDefault: false,
    lastCommitDate: daysAgo(60),
    lastCommitMessage: "feat: CSV export for reports",
    lastCommitAuthor: "hwang.jiyoung",
    ageInDays: 60,
    webUrl: "https://gitlab.example.com/team/our-platform/-/tree/feature/csv-export",
  },
  {
    name: "feature/dark-mode",
    merged: true,
    protected: false,
    isDefault: false,
    lastCommitDate: daysAgo(90),
    lastCommitMessage: "feat: implement dark mode toggle",
    lastCommitAuthor: "shin.dongwook",
    ageInDays: 90,
    webUrl: "https://gitlab.example.com/team/our-platform/-/tree/feature/dark-mode",
  },
  {
    name: "bugfix/memory-leak-websocket",
    merged: true,
    protected: false,
    isDefault: false,
    lastCommitDate: daysAgo(110),
    lastCommitMessage: "fix: properly close WebSocket connections",
    lastCommitAuthor: "yoon.kibum",
    ageInDays: 110,
    webUrl: "https://gitlab.example.com/team/our-platform/-/tree/bugfix/memory-leak-websocket",
  },
  // Temp patterns + stale → delete-recommended
  {
    name: "tmp/test-new-ci-pipeline",
    merged: false,
    protected: false,
    isDefault: false,
    lastCommitDate: daysAgo(120),
    lastCommitMessage: "test CI pipeline changes",
    lastCommitAuthor: "lee.minseok",
    ageInDays: 120,
    webUrl: "https://gitlab.example.com/team/our-platform/-/tree/tmp/test-new-ci-pipeline",
  },
  {
    name: "wip/refactor-auth-module",
    merged: false,
    protected: false,
    isDefault: false,
    lastCommitDate: daysAgo(150),
    lastCommitMessage: "wip: halfway through auth refactor",
    lastCommitAuthor: "bae.seunghee",
    ageInDays: 150,
    webUrl: "https://gitlab.example.com/team/our-platform/-/tree/wip/refactor-auth-module",
  },
  {
    name: "experiment/graphql-migration",
    merged: false,
    protected: false,
    isDefault: false,
    lastCommitDate: daysAgo(200),
    lastCommitMessage: "experiment: trying GraphQL schema first approach",
    lastCommitAuthor: "noh.changmin",
    ageInDays: 200,
    webUrl: "https://gitlab.example.com/team/our-platform/-/tree/experiment/graphql-migration",
  },
  {
    name: "temp/hotfix-attempt",
    merged: false,
    protected: false,
    isDefault: false,
    lastCommitDate: daysAgo(95),
    lastCommitMessage: "temp fix attempt (superseded by hotfix/2.3.1)",
    lastCommitAuthor: "kim.junghyun",
    ageInDays: 95,
    webUrl: "https://gitlab.example.com/team/our-platform/-/tree/temp/hotfix-attempt",
  },
  // Temp patterns + recent → review
  {
    name: "test/ab-test-homepage",
    merged: false,
    protected: false,
    isDefault: false,
    lastCommitDate: daysAgo(10),
    lastCommitMessage: "test: A/B test variant B for homepage",
    lastCommitAuthor: "jung.hyewon",
    ageInDays: 10,
    webUrl: "https://gitlab.example.com/team/our-platform/-/tree/test/ab-test-homepage",
  },
  {
    name: "wip/search-optimization",
    merged: false,
    protected: false,
    isDefault: false,
    lastCommitDate: daysAgo(22),
    lastCommitMessage: "wip: experimenting with elasticsearch",
    lastCommitAuthor: "park.sooyeon",
    ageInDays: 22,
    webUrl: "https://gitlab.example.com/team/our-platform/-/tree/wip/search-optimization",
  },
  // Stale unmerged → review
  {
    name: "feature/legacy-importer",
    merged: false,
    protected: false,
    isDefault: false,
    lastCommitDate: daysAgo(100),
    lastCommitMessage: "feat: importer for v1 data format",
    lastCommitAuthor: "choi.yujin",
    ageInDays: 100,
    webUrl: "https://gitlab.example.com/team/our-platform/-/tree/feature/legacy-importer",
  },
  {
    name: "feature/multi-tenant-support",
    merged: false,
    protected: false,
    isDefault: false,
    lastCommitDate: daysAgo(130),
    lastCommitMessage: "feat: tenant isolation layer draft",
    lastCommitAuthor: "seo.minjae",
    ageInDays: 130,
    webUrl: "https://gitlab.example.com/team/our-platform/-/tree/feature/multi-tenant-support",
  },
  {
    name: "feature/analytics-v2",
    merged: false,
    protected: false,
    isDefault: false,
    lastCommitDate: daysAgo(180),
    lastCommitMessage: "feat: custom event tracking draft",
    lastCommitAuthor: "hwang.jiyoung",
    ageInDays: 180,
    webUrl: "https://gitlab.example.com/team/our-platform/-/tree/feature/analytics-v2",
  },
  // Active safe branches
  {
    name: "chore/update-dependencies",
    merged: false,
    protected: false,
    isDefault: false,
    lastCommitDate: daysAgo(5),
    lastCommitMessage: "chore: bump react to 18.3.1",
    lastCommitAuthor: "oh.seungmin",
    ageInDays: 5,
    webUrl: "https://gitlab.example.com/team/our-platform/-/tree/chore/update-dependencies",
  },
  {
    name: "docs/api-reference-update",
    merged: false,
    protected: false,
    isDefault: false,
    lastCommitDate: daysAgo(8),
    lastCommitMessage: "docs: update REST API reference for v2.4",
    lastCommitAuthor: "shin.dongwook",
    ageInDays: 8,
    webUrl: "https://gitlab.example.com/team/our-platform/-/tree/docs/api-reference-update",
  },
];
